spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}/${DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_ID}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_SERVER_IP}  # Kafka 서버 접속 주소
    consumer:
      group-id: ${KAFKA_GROUP_ID}  # 컨슈머 그룹 식별자
      auto-offset-reset: earliest  # 초기 오프셋(가장 처음 메세지부터 소비)

app:
  oauth:
    redirect-url: https://ubot2.site/

management:
  endpoints:
    web:
      exposure:
        include: health   # 헬스체크용 엔드포인트 노출 (/actuator/health)
  endpoint:
    health:
      show-details: never
